// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (AuthRefreshToken, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (AuthSession, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (AuthUser, error)
	DeleteAllUserSessionsById(ctx context.Context, userID uuid.UUID) error
	DeleteSessionByID(ctx context.Context, id uuid.UUID) error
	GetAllUserSessionToken(ctx context.Context, userID uuid.UUID) ([]string, error)
	GetRefreshTokenByID(ctx context.Context, id uuid.UUID) (AuthRefreshToken, error)
	GetRefreshTokenByToken(ctx context.Context, token string) (AuthRefreshToken, error)
	GetSessionByToken(ctx context.Context, token string) (AuthSession, error)
	GetSessionWithUserInformation(ctx context.Context, id uuid.UUID) (GetSessionWithUserInformationRow, error)
	GetUserByEmail(ctx context.Context, email string) (AuthUser, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (AuthUser, error)
	ListUsers(ctx context.Context) ([]AuthUser, error)
	MarkUsedRefreshTokenByID(ctx context.Context, id uuid.UUID) error
	MarkUsedRefreshTokenByToken(ctx context.Context, token string) error
}

var _ Querier = (*Queries)(nil)
