// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: sessions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO auth.sessions (
    user_id
) VALUES (
    $1
) RETURNING id, user_id, created_at, updated_at
`

func (q *Queries) CreateSession(ctx context.Context, userID pgtype.UUID) (AuthSession, error) {
	row := q.db.QueryRow(ctx, createSession, userID)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
